nmMode: hardlinks-global

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

catalog:
  "@biomejs/biome": 2.3.11
  "@typescript/native-preview": 7.0.0-dev.20260111.1
  "rwsdk": "1.0.0-beta.47"

catalogs:
  "react":
    "react": ^19.2.3
    "react-dom": ^19.2.3
    "react-server-dom-webpack": ^19.2.3
    "@types/react": ^19.2.8
    "@types/react-dom": ^19.2.3
