/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: cd4c3d1312caff6c5dd1946f498d71e8)
export {};
declare global {
	const BUCKET: R2Bucket;
	const DB: D1Database;
	const ASSETS: Fetcher;
}
