// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xa7dc2cd9cf562058n;
export const Envelope_Which = {
  HTTP: 0,
  WS: 1,
  CONTROL: 2
};
export class Envelope extends $.Struct {
  static HTTP = Envelope_Which.HTTP;
  static WS = Envelope_Which.WS;
  static CONTROL = Envelope_Which.CONTROL;
  static _capnp = {
    displayName: "Envelope",
    id: "c8b600439ef0a42e",
    size: new $.ObjectSize(32, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get connectionId() {
    return $.utils.getUint64(8, this);
  }
  set connectionId(value) {
    $.utils.setUint64(8, value, this);
  }
  get streamId() {
    return $.utils.getUint32(16, this);
  }
  set streamId(value) {
    $.utils.setUint32(16, value, this);
  }
  get msgSeq() {
    return $.utils.getUint32(20, this);
  }
  set msgSeq(value) {
    $.utils.setUint32(20, value, this);
  }
  _adoptHttp(value) {
    $.utils.setUint16(24, 0, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHttp() {
    return $.utils.disown(this.http);
  }
  get http() {
    $.utils.testWhich("http", $.utils.getUint16(24, this), 0, this);
    return $.utils.getStruct(0, HttpMessage, this);
  }
  _hasHttp() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHttp() {
    $.utils.setUint16(24, 0, this);
    return $.utils.initStructAt(0, HttpMessage, this);
  }
  get _isHttp() {
    return $.utils.getUint16(24, this) === 0;
  }
  set http(value) {
    $.utils.setUint16(24, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptWs(value) {
    $.utils.setUint16(24, 1, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownWs() {
    return $.utils.disown(this.ws);
  }
  get ws() {
    $.utils.testWhich("ws", $.utils.getUint16(24, this), 1, this);
    return $.utils.getStruct(0, WebSocketFrame, this);
  }
  _hasWs() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initWs() {
    $.utils.setUint16(24, 1, this);
    return $.utils.initStructAt(0, WebSocketFrame, this);
  }
  get _isWs() {
    return $.utils.getUint16(24, this) === 1;
  }
  set ws(value) {
    $.utils.setUint16(24, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptControl(value) {
    $.utils.setUint16(24, 2, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownControl() {
    return $.utils.disown(this.control);
  }
  get control() {
    $.utils.testWhich("control", $.utils.getUint16(24, this), 2, this);
    return $.utils.getStruct(0, Control, this);
  }
  _hasControl() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initControl() {
    $.utils.setUint16(24, 2, this);
    return $.utils.initStructAt(0, Control, this);
  }
  get _isControl() {
    return $.utils.getUint16(24, this) === 2;
  }
  set control(value) {
    $.utils.setUint16(24, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "Envelope_" + super.toString(); }
  which() {
    return $.utils.getUint16(24, this);
  }
}
export const HttpMessage_Which = {
  REQUEST_INIT: 0,
  REQUEST_BODY_CHUNK: 1,
  REQUEST_TRAILERS: 2,
  REQUEST_END: 3,
  REQUEST_ABORT: 4,
  RESPONSE_INIT: 5,
  /**
* 103 Early Hints
*
*/
  RESPONSE_INTERIM: 6,
  RESPONSE_BODY_CHUNK: 7,
  RESPONSE_TRAILERS: 8,
  RESPONSE_END: 9,
  RESPONSE_ABORT: 10
};
export class HttpMessage extends $.Struct {
  static REQUEST_INIT = HttpMessage_Which.REQUEST_INIT;
  static REQUEST_BODY_CHUNK = HttpMessage_Which.REQUEST_BODY_CHUNK;
  static REQUEST_TRAILERS = HttpMessage_Which.REQUEST_TRAILERS;
  static REQUEST_END = HttpMessage_Which.REQUEST_END;
  static REQUEST_ABORT = HttpMessage_Which.REQUEST_ABORT;
  static RESPONSE_INIT = HttpMessage_Which.RESPONSE_INIT;
  static RESPONSE_INTERIM = HttpMessage_Which.RESPONSE_INTERIM;
  static RESPONSE_BODY_CHUNK = HttpMessage_Which.RESPONSE_BODY_CHUNK;
  static RESPONSE_TRAILERS = HttpMessage_Which.RESPONSE_TRAILERS;
  static RESPONSE_END = HttpMessage_Which.RESPONSE_END;
  static RESPONSE_ABORT = HttpMessage_Which.RESPONSE_ABORT;
  static _capnp = {
    displayName: "HttpMessage",
    id: "857c7ddbc91a4c08",
    size: new $.ObjectSize(8, 1),
  };
  _adoptRequestInit(value) {
    $.utils.setUint16(0, 0, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestInit() {
    return $.utils.disown(this.requestInit);
  }
  get requestInit() {
    $.utils.testWhich("requestInit", $.utils.getUint16(0, this), 0, this);
    return $.utils.getStruct(0, HttpRequestInit, this);
  }
  _hasRequestInit() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestInit() {
    $.utils.setUint16(0, 0, this);
    return $.utils.initStructAt(0, HttpRequestInit, this);
  }
  get _isRequestInit() {
    return $.utils.getUint16(0, this) === 0;
  }
  set requestInit(value) {
    $.utils.setUint16(0, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestBodyChunk(value) {
    $.utils.setUint16(0, 1, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestBodyChunk() {
    return $.utils.disown(this.requestBodyChunk);
  }
  get requestBodyChunk() {
    $.utils.testWhich("requestBodyChunk", $.utils.getUint16(0, this), 1, this);
    return $.utils.getStruct(0, HttpBodyChunk, this);
  }
  _hasRequestBodyChunk() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestBodyChunk() {
    $.utils.setUint16(0, 1, this);
    return $.utils.initStructAt(0, HttpBodyChunk, this);
  }
  get _isRequestBodyChunk() {
    return $.utils.getUint16(0, this) === 1;
  }
  set requestBodyChunk(value) {
    $.utils.setUint16(0, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestTrailers(value) {
    $.utils.setUint16(0, 2, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestTrailers() {
    return $.utils.disown(this.requestTrailers);
  }
  get requestTrailers() {
    $.utils.testWhich("requestTrailers", $.utils.getUint16(0, this), 2, this);
    return $.utils.getStruct(0, HttpTrailers, this);
  }
  _hasRequestTrailers() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestTrailers() {
    $.utils.setUint16(0, 2, this);
    return $.utils.initStructAt(0, HttpTrailers, this);
  }
  get _isRequestTrailers() {
    return $.utils.getUint16(0, this) === 2;
  }
  set requestTrailers(value) {
    $.utils.setUint16(0, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestEnd(value) {
    $.utils.setUint16(0, 3, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestEnd() {
    return $.utils.disown(this.requestEnd);
  }
  get requestEnd() {
    $.utils.testWhich("requestEnd", $.utils.getUint16(0, this), 3, this);
    return $.utils.getStruct(0, HttpRequestEnd, this);
  }
  _hasRequestEnd() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestEnd() {
    $.utils.setUint16(0, 3, this);
    return $.utils.initStructAt(0, HttpRequestEnd, this);
  }
  get _isRequestEnd() {
    return $.utils.getUint16(0, this) === 3;
  }
  set requestEnd(value) {
    $.utils.setUint16(0, 3, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestAbort(value) {
    $.utils.setUint16(0, 4, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestAbort() {
    return $.utils.disown(this.requestAbort);
  }
  get requestAbort() {
    $.utils.testWhich("requestAbort", $.utils.getUint16(0, this), 4, this);
    return $.utils.getStruct(0, HttpRequestAbort, this);
  }
  _hasRequestAbort() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestAbort() {
    $.utils.setUint16(0, 4, this);
    return $.utils.initStructAt(0, HttpRequestAbort, this);
  }
  get _isRequestAbort() {
    return $.utils.getUint16(0, this) === 4;
  }
  set requestAbort(value) {
    $.utils.setUint16(0, 4, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseInit(value) {
    $.utils.setUint16(0, 5, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseInit() {
    return $.utils.disown(this.responseInit);
  }
  get responseInit() {
    $.utils.testWhich("responseInit", $.utils.getUint16(0, this), 5, this);
    return $.utils.getStruct(0, HttpResponseInit, this);
  }
  _hasResponseInit() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseInit() {
    $.utils.setUint16(0, 5, this);
    return $.utils.initStructAt(0, HttpResponseInit, this);
  }
  get _isResponseInit() {
    return $.utils.getUint16(0, this) === 5;
  }
  set responseInit(value) {
    $.utils.setUint16(0, 5, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseInterim(value) {
    $.utils.setUint16(0, 6, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseInterim() {
    return $.utils.disown(this.responseInterim);
  }
  /**
* 103 Early Hints
*
*/
  get responseInterim() {
    $.utils.testWhich("responseInterim", $.utils.getUint16(0, this), 6, this);
    return $.utils.getStruct(0, HttpInterimResponse, this);
  }
  _hasResponseInterim() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseInterim() {
    $.utils.setUint16(0, 6, this);
    return $.utils.initStructAt(0, HttpInterimResponse, this);
  }
  get _isResponseInterim() {
    return $.utils.getUint16(0, this) === 6;
  }
  set responseInterim(value) {
    $.utils.setUint16(0, 6, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseBodyChunk(value) {
    $.utils.setUint16(0, 7, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseBodyChunk() {
    return $.utils.disown(this.responseBodyChunk);
  }
  get responseBodyChunk() {
    $.utils.testWhich("responseBodyChunk", $.utils.getUint16(0, this), 7, this);
    return $.utils.getStruct(0, HttpBodyChunk, this);
  }
  _hasResponseBodyChunk() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseBodyChunk() {
    $.utils.setUint16(0, 7, this);
    return $.utils.initStructAt(0, HttpBodyChunk, this);
  }
  get _isResponseBodyChunk() {
    return $.utils.getUint16(0, this) === 7;
  }
  set responseBodyChunk(value) {
    $.utils.setUint16(0, 7, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseTrailers(value) {
    $.utils.setUint16(0, 8, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseTrailers() {
    return $.utils.disown(this.responseTrailers);
  }
  get responseTrailers() {
    $.utils.testWhich("responseTrailers", $.utils.getUint16(0, this), 8, this);
    return $.utils.getStruct(0, HttpTrailers, this);
  }
  _hasResponseTrailers() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseTrailers() {
    $.utils.setUint16(0, 8, this);
    return $.utils.initStructAt(0, HttpTrailers, this);
  }
  get _isResponseTrailers() {
    return $.utils.getUint16(0, this) === 8;
  }
  set responseTrailers(value) {
    $.utils.setUint16(0, 8, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseEnd(value) {
    $.utils.setUint16(0, 9, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseEnd() {
    return $.utils.disown(this.responseEnd);
  }
  get responseEnd() {
    $.utils.testWhich("responseEnd", $.utils.getUint16(0, this), 9, this);
    return $.utils.getStruct(0, HttpResponseEnd, this);
  }
  _hasResponseEnd() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseEnd() {
    $.utils.setUint16(0, 9, this);
    return $.utils.initStructAt(0, HttpResponseEnd, this);
  }
  get _isResponseEnd() {
    return $.utils.getUint16(0, this) === 9;
  }
  set responseEnd(value) {
    $.utils.setUint16(0, 9, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseAbort(value) {
    $.utils.setUint16(0, 10, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseAbort() {
    return $.utils.disown(this.responseAbort);
  }
  get responseAbort() {
    $.utils.testWhich("responseAbort", $.utils.getUint16(0, this), 10, this);
    return $.utils.getStruct(0, HttpResponseAbort, this);
  }
  _hasResponseAbort() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseAbort() {
    $.utils.setUint16(0, 10, this);
    return $.utils.initStructAt(0, HttpResponseAbort, this);
  }
  get _isResponseAbort() {
    return $.utils.getUint16(0, this) === 10;
  }
  set responseAbort(value) {
    $.utils.setUint16(0, 10, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "HttpMessage_" + super.toString(); }
  which() {
    return $.utils.getUint16(0, this);
  }
}
export class HttpRequestInit extends $.Struct {
  static _capnp = {
    displayName: "HttpRequestInit",
    id: "eae47d0497139b13",
    size: new $.ObjectSize(16, 3),
  };
  static _Headers;
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get method() {
    return $.utils.getText(0, this);
  }
  set method(value) {
    $.utils.setText(0, value, this);
  }
  get uri() {
    return $.utils.getText(1, this);
  }
  set uri(value) {
    $.utils.setText(1, value, this);
  }
  get version() {
    return $.utils.getUint16(8, this);
  }
  set version(value) {
    $.utils.setUint16(8, value, this);
  }
  _adoptHeaders(value) {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownHeaders() {
    return $.utils.disown(this.headers);
  }
  get headers() {
    return $.utils.getList(2, HttpRequestInit._Headers, this);
  }
  _hasHeaders() {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initHeaders(length) {
    return $.utils.initList(2, HttpRequestInit._Headers, length, this);
  }
  set headers(value) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  get hasBody() {
    return $.utils.getBit(80, this);
  }
  set hasBody(value) {
    $.utils.setBit(80, value, this);
  }
  toString() { return "HttpRequestInit_" + super.toString(); }
}
export class HttpRequestEnd extends $.Struct {
  static _capnp = {
    displayName: "HttpRequestEnd",
    id: "bc503621daab0632",
    size: new $.ObjectSize(8, 0),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  toString() { return "HttpRequestEnd_" + super.toString(); }
}
export class HttpRequestAbort extends $.Struct {
  static _capnp = {
    displayName: "HttpRequestAbort",
    id: "d398bed8ef2f867f",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get reason() {
    return $.utils.getUint16(8, this);
  }
  set reason(value) {
    $.utils.setUint16(8, value, this);
  }
  get detail() {
    return $.utils.getText(0, this);
  }
  set detail(value) {
    $.utils.setText(0, value, this);
  }
  toString() { return "HttpRequestAbort_" + super.toString(); }
}
export class HttpResponseInit extends $.Struct {
  static _capnp = {
    displayName: "HttpResponseInit",
    id: "dc7bd14baf7c6e4d",
    size: new $.ObjectSize(24, 1),
  };
  static _Headers;
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  /**
* 200, 404, ...
*
*/
  get status() {
    return $.utils.getUint16(8, this);
  }
  set status(value) {
    $.utils.setUint16(8, value, this);
  }
  _adoptHeaders(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHeaders() {
    return $.utils.disown(this.headers);
  }
  get headers() {
    return $.utils.getList(0, HttpResponseInit._Headers, this);
  }
  _hasHeaders() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHeaders(length) {
    return $.utils.initList(0, HttpResponseInit._Headers, length, this);
  }
  set headers(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get hasBody() {
    return $.utils.getBit(80, this);
  }
  set hasBody(value) {
    $.utils.setBit(80, value, this);
  }
  /**
* 0=unknown
*
*/
  get contentLength() {
    return $.utils.getUint64(16, this);
  }
  set contentLength(value) {
    $.utils.setUint64(16, value, this);
  }
  toString() { return "HttpResponseInit_" + super.toString(); }
}
export class HttpInterimResponse extends $.Struct {
  static _capnp = {
    displayName: "HttpInterimResponse",
    id: "fca1a2f0457d915f",
    size: new $.ObjectSize(16, 1),
  };
  static _Headers;
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  /**
* 100-199
*
*/
  get status() {
    return $.utils.getUint16(8, this);
  }
  set status(value) {
    $.utils.setUint16(8, value, this);
  }
  _adoptHeaders(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHeaders() {
    return $.utils.disown(this.headers);
  }
  get headers() {
    return $.utils.getList(0, HttpInterimResponse._Headers, this);
  }
  _hasHeaders() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHeaders(length) {
    return $.utils.initList(0, HttpInterimResponse._Headers, length, this);
  }
  set headers(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "HttpInterimResponse_" + super.toString(); }
}
export class HttpBodyChunk extends $.Struct {
  static _capnp = {
    displayName: "HttpBodyChunk",
    id: "e9e3d78bd9d9c03b",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  _adoptData(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData() {
    return $.utils.disown(this.data);
  }
  get data() {
    return $.utils.getData(0, this);
  }
  _hasData() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length) {
    return $.utils.initData(0, length, this);
  }
  set data(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get seq() {
    return $.utils.getUint32(8, this);
  }
  set seq(value) {
    $.utils.setUint32(8, value, this);
  }
  get isLast() {
    return $.utils.getBit(96, this);
  }
  set isLast(value) {
    $.utils.setBit(96, value, this);
  }
  toString() { return "HttpBodyChunk_" + super.toString(); }
}
export class HttpTrailers extends $.Struct {
  static _capnp = {
    displayName: "HttpTrailers",
    id: "a5e3baf5fe7303e1",
    size: new $.ObjectSize(8, 1),
  };
  static _Headers;
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  _adoptHeaders(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHeaders() {
    return $.utils.disown(this.headers);
  }
  get headers() {
    return $.utils.getList(0, HttpTrailers._Headers, this);
  }
  _hasHeaders() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHeaders(length) {
    return $.utils.initList(0, HttpTrailers._Headers, length, this);
  }
  set headers(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "HttpTrailers_" + super.toString(); }
}
export class HttpResponseEnd extends $.Struct {
  static _capnp = {
    displayName: "HttpResponseEnd",
    id: "854bb133649d198a",
    size: new $.ObjectSize(8, 0),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  toString() { return "HttpResponseEnd_" + super.toString(); }
}
export class HttpResponseAbort extends $.Struct {
  static _capnp = {
    displayName: "HttpResponseAbort",
    id: "d544e3cab9996b62",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get reason() {
    return $.utils.getUint16(8, this);
  }
  set reason(value) {
    $.utils.setUint16(8, value, this);
  }
  get detail() {
    return $.utils.getText(0, this);
  }
  set detail(value) {
    $.utils.setText(0, value, this);
  }
  toString() { return "HttpResponseAbort_" + super.toString(); }
}
export const HttpVersion = {
  /**
* HTTP/1.1
*
*/
  H1: 0,
  /**
* HTTP/2
* h3 is not supported;
*
*/
  H2: 1
};
export const AbortReason = {
  UNKNOWN: 0,
  TIMEOUT: 1,
  PEER_CLOSED: 2,
  RESET_BY_PEER: 3,
  CONNECTION_LOST: 4,
  CANCELLED: 5,
  PROTOCOL_ERROR: 6,
  FLOW_CONTROL: 7,
  OVERLOAD: 8
};
export class Header extends $.Struct {
  static _capnp = {
    displayName: "Header",
    id: "84455f8078b27db9",
    size: new $.ObjectSize(0, 2),
  };
  get name() {
    return $.utils.getText(0, this);
  }
  set name(value) {
    $.utils.setText(0, value, this);
  }
  _adoptValue(value) {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownValue() {
    return $.utils.disown(this.value);
  }
  get value() {
    return $.utils.getData(1, this);
  }
  _hasValue() {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initValue(length) {
    return $.utils.initData(1, length, this);
  }
  set value(value) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString() { return "Header_" + super.toString(); }
}
export const WebSocketOpcode = {
  CONTINUATION: 0,
  TEXT: 1,
  BINARY: 2,
  CLOSE: 3,
  PING: 4,
  PONG: 5
};
export class WebSocketFrame extends $.Struct {
  static _capnp = {
    displayName: "WebSocketFrame",
    id: "c7a9aec0e8febcc8",
    size: new $.ObjectSize(24, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get fin() {
    return $.utils.getBit(64, this);
  }
  set fin(value) {
    $.utils.setBit(64, value, this);
  }
  get rsv1() {
    return $.utils.getBit(65, this);
  }
  set rsv1(value) {
    $.utils.setBit(65, value, this);
  }
  get rsv2() {
    return $.utils.getBit(66, this);
  }
  set rsv2(value) {
    $.utils.setBit(66, value, this);
  }
  get rsv3() {
    return $.utils.getBit(67, this);
  }
  set rsv3(value) {
    $.utils.setBit(67, value, this);
  }
  get opcode() {
    return $.utils.getUint16(10, this);
  }
  set opcode(value) {
    $.utils.setUint16(10, value, this);
  }
  get masked() {
    return $.utils.getBit(68, this);
  }
  set masked(value) {
    $.utils.setBit(68, value, this);
  }
  get maskKey() {
    return $.utils.getUint32(12, this);
  }
  set maskKey(value) {
    $.utils.setUint32(12, value, this);
  }
  _adoptPayload(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownPayload() {
    return $.utils.disown(this.payload);
  }
  get payload() {
    return $.utils.getData(0, this);
  }
  _hasPayload() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initPayload(length) {
    return $.utils.initData(0, length, this);
  }
  set payload(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get closeCode() {
    return $.utils.getUint16(16, this);
  }
  set closeCode(value) {
    $.utils.setUint16(16, value, this);
  }
  toString() { return "WebSocketFrame_" + super.toString(); }
}
export const Control_Which = {
  PING: 0,
  PONG: 1,
  FLOW_WINDOW_UPDATE: 2,
  ERROR: 3,
  GO_AWAY: 4
};
export class Control extends $.Struct {
  static PING = Control_Which.PING;
  static PONG = Control_Which.PONG;
  static FLOW_WINDOW_UPDATE = Control_Which.FLOW_WINDOW_UPDATE;
  static ERROR = Control_Which.ERROR;
  static GO_AWAY = Control_Which.GO_AWAY;
  static _capnp = {
    displayName: "Control",
    id: "f19164b12011f28c",
    size: new $.ObjectSize(8, 1),
  };
  _adoptPing(value) {
    $.utils.setUint16(0, 0, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownPing() {
    return $.utils.disown(this.ping);
  }
  get ping() {
    $.utils.testWhich("ping", $.utils.getUint16(0, this), 0, this);
    return $.utils.getStruct(0, Ping, this);
  }
  _hasPing() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initPing() {
    $.utils.setUint16(0, 0, this);
    return $.utils.initStructAt(0, Ping, this);
  }
  get _isPing() {
    return $.utils.getUint16(0, this) === 0;
  }
  set ping(value) {
    $.utils.setUint16(0, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptPong(value) {
    $.utils.setUint16(0, 1, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownPong() {
    return $.utils.disown(this.pong);
  }
  get pong() {
    $.utils.testWhich("pong", $.utils.getUint16(0, this), 1, this);
    return $.utils.getStruct(0, Pong, this);
  }
  _hasPong() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initPong() {
    $.utils.setUint16(0, 1, this);
    return $.utils.initStructAt(0, Pong, this);
  }
  get _isPong() {
    return $.utils.getUint16(0, this) === 1;
  }
  set pong(value) {
    $.utils.setUint16(0, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptFlowWindowUpdate(value) {
    $.utils.setUint16(0, 2, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownFlowWindowUpdate() {
    return $.utils.disown(this.flowWindowUpdate);
  }
  get flowWindowUpdate() {
    $.utils.testWhich("flowWindowUpdate", $.utils.getUint16(0, this), 2, this);
    return $.utils.getStruct(0, FlowWindowUpdate, this);
  }
  _hasFlowWindowUpdate() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initFlowWindowUpdate() {
    $.utils.setUint16(0, 2, this);
    return $.utils.initStructAt(0, FlowWindowUpdate, this);
  }
  get _isFlowWindowUpdate() {
    return $.utils.getUint16(0, this) === 2;
  }
  set flowWindowUpdate(value) {
    $.utils.setUint16(0, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptError(value) {
    $.utils.setUint16(0, 3, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownError() {
    return $.utils.disown(this.error);
  }
  get error() {
    $.utils.testWhich("error", $.utils.getUint16(0, this), 3, this);
    return $.utils.getStruct(0, ErrorReport, this);
  }
  _hasError() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initError() {
    $.utils.setUint16(0, 3, this);
    return $.utils.initStructAt(0, ErrorReport, this);
  }
  get _isError() {
    return $.utils.getUint16(0, this) === 3;
  }
  set error(value) {
    $.utils.setUint16(0, 3, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptGoAway(value) {
    $.utils.setUint16(0, 4, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownGoAway() {
    return $.utils.disown(this.goAway);
  }
  get goAway() {
    $.utils.testWhich("goAway", $.utils.getUint16(0, this), 4, this);
    return $.utils.getStruct(0, GoAway, this);
  }
  _hasGoAway() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initGoAway() {
    $.utils.setUint16(0, 4, this);
    return $.utils.initStructAt(0, GoAway, this);
  }
  get _isGoAway() {
    return $.utils.getUint16(0, this) === 4;
  }
  set goAway(value) {
    $.utils.setUint16(0, 4, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "Control_" + super.toString(); }
  which() {
    return $.utils.getUint16(0, this);
  }
}
export class Ping extends $.Struct {
  static _capnp = {
    displayName: "Ping",
    id: "e6be57830fd0468e",
    size: new $.ObjectSize(8, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  _adoptData(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData() {
    return $.utils.disown(this.data);
  }
  get data() {
    return $.utils.getData(0, this);
  }
  _hasData() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length) {
    return $.utils.initData(0, length, this);
  }
  set data(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "Ping_" + super.toString(); }
}
export class Pong extends $.Struct {
  static _capnp = {
    displayName: "Pong",
    id: "d6cf54316473cd3f",
    size: new $.ObjectSize(8, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  _adoptData(value) {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData() {
    return $.utils.disown(this.data);
  }
  get data() {
    return $.utils.getData(0, this);
  }
  _hasData() {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length) {
    return $.utils.initData(0, length, this);
  }
  set data(value) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString() { return "Pong_" + super.toString(); }
}
export class FlowWindowUpdate extends $.Struct {
  static _capnp = {
    displayName: "FlowWindowUpdate",
    id: "e826c39bc9b96521",
    size: new $.ObjectSize(16, 0),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get availableSendBytes() {
    return $.utils.getUint32(8, this);
  }
  set availableSendBytes(value) {
    $.utils.setUint32(8, value, this);
  }
  toString() { return "FlowWindowUpdate_" + super.toString(); }
}
export class ErrorReport extends $.Struct {
  static _capnp = {
    displayName: "ErrorReport",
    id: "97f57fee4e4b6550",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get code() {
    return $.utils.getUint32(8, this);
  }
  set code(value) {
    $.utils.setUint32(8, value, this);
  }
  get message() {
    return $.utils.getText(0, this);
  }
  set message(value) {
    $.utils.setText(0, value, this);
  }
  toString() { return "ErrorReport_" + super.toString(); }
}
export class GoAway extends $.Struct {
  static _capnp = {
    displayName: "GoAway",
    id: "d552cd9f59680575",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs() {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value) {
    $.utils.setUint64(0, value, this);
  }
  get lastMsgSeq() {
    return $.utils.getUint32(8, this);
  }
  set lastMsgSeq(value) {
    $.utils.setUint32(8, value, this);
  }
  get reason() {
    return $.utils.getText(0, this);
  }
  set reason(value) {
    $.utils.setText(0, value, this);
  }
  toString() { return "GoAway_" + super.toString(); }
}
HttpRequestInit._Headers = $.CompositeList(Header);
HttpResponseInit._Headers = $.CompositeList(Header);
HttpInterimResponse._Headers = $.CompositeList(Header);
HttpTrailers._Headers = $.CompositeList(Header);
