// This file has been automatically generated by capnp-es.
// biome-ignore-all lint: Generated code
import * as $ from "capnp-es";
export const _capnpFileId = 0xa7dc2cd9cf562058n;
export const Envelope_Which = {
  HTTP: 0,
  WS: 1,
  CONTROL: 2,
} as const;
export type Envelope_Which =
  (typeof Envelope_Which)[keyof typeof Envelope_Which];
export class Envelope extends $.Struct {
  static readonly HTTP = Envelope_Which.HTTP;
  static readonly WS = Envelope_Which.WS;
  static readonly CONTROL = Envelope_Which.CONTROL;
  static readonly _capnp = {
    displayName: "Envelope",
    id: "c8b600439ef0a42e",
    size: new $.ObjectSize(32, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get connectionId(): bigint {
    return $.utils.getUint64(8, this);
  }
  set connectionId(value: bigint) {
    $.utils.setUint64(8, value, this);
  }
  get streamId(): number {
    return $.utils.getUint32(16, this);
  }
  set streamId(value: number) {
    $.utils.setUint32(16, value, this);
  }
  get msgSeq(): number {
    return $.utils.getUint32(20, this);
  }
  set msgSeq(value: number) {
    $.utils.setUint32(20, value, this);
  }
  _adoptHttp(value: $.Orphan<HttpMessage>): void {
    $.utils.setUint16(24, 0, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHttp(): $.Orphan<HttpMessage> {
    return $.utils.disown(this.http);
  }
  get http(): HttpMessage {
    $.utils.testWhich("http", $.utils.getUint16(24, this), 0, this);
    return $.utils.getStruct(0, HttpMessage, this);
  }
  _hasHttp(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHttp(): HttpMessage {
    $.utils.setUint16(24, 0, this);
    return $.utils.initStructAt(0, HttpMessage, this);
  }
  get _isHttp(): boolean {
    return $.utils.getUint16(24, this) === 0;
  }
  set http(value: HttpMessage) {
    $.utils.setUint16(24, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptWs(value: $.Orphan<WebSocketFrame>): void {
    $.utils.setUint16(24, 1, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownWs(): $.Orphan<WebSocketFrame> {
    return $.utils.disown(this.ws);
  }
  get ws(): WebSocketFrame {
    $.utils.testWhich("ws", $.utils.getUint16(24, this), 1, this);
    return $.utils.getStruct(0, WebSocketFrame, this);
  }
  _hasWs(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initWs(): WebSocketFrame {
    $.utils.setUint16(24, 1, this);
    return $.utils.initStructAt(0, WebSocketFrame, this);
  }
  get _isWs(): boolean {
    return $.utils.getUint16(24, this) === 1;
  }
  set ws(value: WebSocketFrame) {
    $.utils.setUint16(24, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptControl(value: $.Orphan<Control>): void {
    $.utils.setUint16(24, 2, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownControl(): $.Orphan<Control> {
    return $.utils.disown(this.control);
  }
  get control(): Control {
    $.utils.testWhich("control", $.utils.getUint16(24, this), 2, this);
    return $.utils.getStruct(0, Control, this);
  }
  _hasControl(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initControl(): Control {
    $.utils.setUint16(24, 2, this);
    return $.utils.initStructAt(0, Control, this);
  }
  get _isControl(): boolean {
    return $.utils.getUint16(24, this) === 2;
  }
  set control(value: Control) {
    $.utils.setUint16(24, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "Envelope_" + super.toString();
  }
  which(): Envelope_Which {
    return $.utils.getUint16(24, this) as Envelope_Which;
  }
}
export const HttpMessage_Which = {
  REQUEST_INIT: 0,
  REQUEST_BODY_CHUNK: 1,
  REQUEST_TRAILERS: 2,
  REQUEST_END: 3,
  REQUEST_ABORT: 4,
  RESPONSE_INIT: 5,
  /**
   * 103 Early Hints
   *
   */
  RESPONSE_INTERIM: 6,
  RESPONSE_BODY_CHUNK: 7,
  RESPONSE_TRAILERS: 8,
  RESPONSE_END: 9,
  RESPONSE_ABORT: 10,
} as const;
export type HttpMessage_Which =
  (typeof HttpMessage_Which)[keyof typeof HttpMessage_Which];
export class HttpMessage extends $.Struct {
  static readonly REQUEST_INIT = HttpMessage_Which.REQUEST_INIT;
  static readonly REQUEST_BODY_CHUNK = HttpMessage_Which.REQUEST_BODY_CHUNK;
  static readonly REQUEST_TRAILERS = HttpMessage_Which.REQUEST_TRAILERS;
  static readonly REQUEST_END = HttpMessage_Which.REQUEST_END;
  static readonly REQUEST_ABORT = HttpMessage_Which.REQUEST_ABORT;
  static readonly RESPONSE_INIT = HttpMessage_Which.RESPONSE_INIT;
  static readonly RESPONSE_INTERIM = HttpMessage_Which.RESPONSE_INTERIM;
  static readonly RESPONSE_BODY_CHUNK = HttpMessage_Which.RESPONSE_BODY_CHUNK;
  static readonly RESPONSE_TRAILERS = HttpMessage_Which.RESPONSE_TRAILERS;
  static readonly RESPONSE_END = HttpMessage_Which.RESPONSE_END;
  static readonly RESPONSE_ABORT = HttpMessage_Which.RESPONSE_ABORT;
  static readonly _capnp = {
    displayName: "HttpMessage",
    id: "857c7ddbc91a4c08",
    size: new $.ObjectSize(8, 1),
  };
  _adoptRequestInit(value: $.Orphan<HttpRequestInit>): void {
    $.utils.setUint16(0, 0, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestInit(): $.Orphan<HttpRequestInit> {
    return $.utils.disown(this.requestInit);
  }
  get requestInit(): HttpRequestInit {
    $.utils.testWhich("requestInit", $.utils.getUint16(0, this), 0, this);
    return $.utils.getStruct(0, HttpRequestInit, this);
  }
  _hasRequestInit(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestInit(): HttpRequestInit {
    $.utils.setUint16(0, 0, this);
    return $.utils.initStructAt(0, HttpRequestInit, this);
  }
  get _isRequestInit(): boolean {
    return $.utils.getUint16(0, this) === 0;
  }
  set requestInit(value: HttpRequestInit) {
    $.utils.setUint16(0, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestBodyChunk(value: $.Orphan<HttpBodyChunk>): void {
    $.utils.setUint16(0, 1, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestBodyChunk(): $.Orphan<HttpBodyChunk> {
    return $.utils.disown(this.requestBodyChunk);
  }
  get requestBodyChunk(): HttpBodyChunk {
    $.utils.testWhich("requestBodyChunk", $.utils.getUint16(0, this), 1, this);
    return $.utils.getStruct(0, HttpBodyChunk, this);
  }
  _hasRequestBodyChunk(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestBodyChunk(): HttpBodyChunk {
    $.utils.setUint16(0, 1, this);
    return $.utils.initStructAt(0, HttpBodyChunk, this);
  }
  get _isRequestBodyChunk(): boolean {
    return $.utils.getUint16(0, this) === 1;
  }
  set requestBodyChunk(value: HttpBodyChunk) {
    $.utils.setUint16(0, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestTrailers(value: $.Orphan<HttpTrailers>): void {
    $.utils.setUint16(0, 2, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestTrailers(): $.Orphan<HttpTrailers> {
    return $.utils.disown(this.requestTrailers);
  }
  get requestTrailers(): HttpTrailers {
    $.utils.testWhich("requestTrailers", $.utils.getUint16(0, this), 2, this);
    return $.utils.getStruct(0, HttpTrailers, this);
  }
  _hasRequestTrailers(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestTrailers(): HttpTrailers {
    $.utils.setUint16(0, 2, this);
    return $.utils.initStructAt(0, HttpTrailers, this);
  }
  get _isRequestTrailers(): boolean {
    return $.utils.getUint16(0, this) === 2;
  }
  set requestTrailers(value: HttpTrailers) {
    $.utils.setUint16(0, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestEnd(value: $.Orphan<HttpRequestEnd>): void {
    $.utils.setUint16(0, 3, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestEnd(): $.Orphan<HttpRequestEnd> {
    return $.utils.disown(this.requestEnd);
  }
  get requestEnd(): HttpRequestEnd {
    $.utils.testWhich("requestEnd", $.utils.getUint16(0, this), 3, this);
    return $.utils.getStruct(0, HttpRequestEnd, this);
  }
  _hasRequestEnd(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestEnd(): HttpRequestEnd {
    $.utils.setUint16(0, 3, this);
    return $.utils.initStructAt(0, HttpRequestEnd, this);
  }
  get _isRequestEnd(): boolean {
    return $.utils.getUint16(0, this) === 3;
  }
  set requestEnd(value: HttpRequestEnd) {
    $.utils.setUint16(0, 3, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptRequestAbort(value: $.Orphan<HttpRequestAbort>): void {
    $.utils.setUint16(0, 4, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownRequestAbort(): $.Orphan<HttpRequestAbort> {
    return $.utils.disown(this.requestAbort);
  }
  get requestAbort(): HttpRequestAbort {
    $.utils.testWhich("requestAbort", $.utils.getUint16(0, this), 4, this);
    return $.utils.getStruct(0, HttpRequestAbort, this);
  }
  _hasRequestAbort(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initRequestAbort(): HttpRequestAbort {
    $.utils.setUint16(0, 4, this);
    return $.utils.initStructAt(0, HttpRequestAbort, this);
  }
  get _isRequestAbort(): boolean {
    return $.utils.getUint16(0, this) === 4;
  }
  set requestAbort(value: HttpRequestAbort) {
    $.utils.setUint16(0, 4, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseInit(value: $.Orphan<HttpResponseInit>): void {
    $.utils.setUint16(0, 5, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseInit(): $.Orphan<HttpResponseInit> {
    return $.utils.disown(this.responseInit);
  }
  get responseInit(): HttpResponseInit {
    $.utils.testWhich("responseInit", $.utils.getUint16(0, this), 5, this);
    return $.utils.getStruct(0, HttpResponseInit, this);
  }
  _hasResponseInit(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseInit(): HttpResponseInit {
    $.utils.setUint16(0, 5, this);
    return $.utils.initStructAt(0, HttpResponseInit, this);
  }
  get _isResponseInit(): boolean {
    return $.utils.getUint16(0, this) === 5;
  }
  set responseInit(value: HttpResponseInit) {
    $.utils.setUint16(0, 5, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseInterim(value: $.Orphan<HttpInterimResponse>): void {
    $.utils.setUint16(0, 6, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseInterim(): $.Orphan<HttpInterimResponse> {
    return $.utils.disown(this.responseInterim);
  }
  /**
   * 103 Early Hints
   *
   */
  get responseInterim(): HttpInterimResponse {
    $.utils.testWhich("responseInterim", $.utils.getUint16(0, this), 6, this);
    return $.utils.getStruct(0, HttpInterimResponse, this);
  }
  _hasResponseInterim(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseInterim(): HttpInterimResponse {
    $.utils.setUint16(0, 6, this);
    return $.utils.initStructAt(0, HttpInterimResponse, this);
  }
  get _isResponseInterim(): boolean {
    return $.utils.getUint16(0, this) === 6;
  }
  set responseInterim(value: HttpInterimResponse) {
    $.utils.setUint16(0, 6, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseBodyChunk(value: $.Orphan<HttpBodyChunk>): void {
    $.utils.setUint16(0, 7, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseBodyChunk(): $.Orphan<HttpBodyChunk> {
    return $.utils.disown(this.responseBodyChunk);
  }
  get responseBodyChunk(): HttpBodyChunk {
    $.utils.testWhich("responseBodyChunk", $.utils.getUint16(0, this), 7, this);
    return $.utils.getStruct(0, HttpBodyChunk, this);
  }
  _hasResponseBodyChunk(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseBodyChunk(): HttpBodyChunk {
    $.utils.setUint16(0, 7, this);
    return $.utils.initStructAt(0, HttpBodyChunk, this);
  }
  get _isResponseBodyChunk(): boolean {
    return $.utils.getUint16(0, this) === 7;
  }
  set responseBodyChunk(value: HttpBodyChunk) {
    $.utils.setUint16(0, 7, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseTrailers(value: $.Orphan<HttpTrailers>): void {
    $.utils.setUint16(0, 8, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseTrailers(): $.Orphan<HttpTrailers> {
    return $.utils.disown(this.responseTrailers);
  }
  get responseTrailers(): HttpTrailers {
    $.utils.testWhich("responseTrailers", $.utils.getUint16(0, this), 8, this);
    return $.utils.getStruct(0, HttpTrailers, this);
  }
  _hasResponseTrailers(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseTrailers(): HttpTrailers {
    $.utils.setUint16(0, 8, this);
    return $.utils.initStructAt(0, HttpTrailers, this);
  }
  get _isResponseTrailers(): boolean {
    return $.utils.getUint16(0, this) === 8;
  }
  set responseTrailers(value: HttpTrailers) {
    $.utils.setUint16(0, 8, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseEnd(value: $.Orphan<HttpResponseEnd>): void {
    $.utils.setUint16(0, 9, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseEnd(): $.Orphan<HttpResponseEnd> {
    return $.utils.disown(this.responseEnd);
  }
  get responseEnd(): HttpResponseEnd {
    $.utils.testWhich("responseEnd", $.utils.getUint16(0, this), 9, this);
    return $.utils.getStruct(0, HttpResponseEnd, this);
  }
  _hasResponseEnd(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseEnd(): HttpResponseEnd {
    $.utils.setUint16(0, 9, this);
    return $.utils.initStructAt(0, HttpResponseEnd, this);
  }
  get _isResponseEnd(): boolean {
    return $.utils.getUint16(0, this) === 9;
  }
  set responseEnd(value: HttpResponseEnd) {
    $.utils.setUint16(0, 9, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptResponseAbort(value: $.Orphan<HttpResponseAbort>): void {
    $.utils.setUint16(0, 10, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownResponseAbort(): $.Orphan<HttpResponseAbort> {
    return $.utils.disown(this.responseAbort);
  }
  get responseAbort(): HttpResponseAbort {
    $.utils.testWhich("responseAbort", $.utils.getUint16(0, this), 10, this);
    return $.utils.getStruct(0, HttpResponseAbort, this);
  }
  _hasResponseAbort(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initResponseAbort(): HttpResponseAbort {
    $.utils.setUint16(0, 10, this);
    return $.utils.initStructAt(0, HttpResponseAbort, this);
  }
  get _isResponseAbort(): boolean {
    return $.utils.getUint16(0, this) === 10;
  }
  set responseAbort(value: HttpResponseAbort) {
    $.utils.setUint16(0, 10, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "HttpMessage_" + super.toString();
  }
  which(): HttpMessage_Which {
    return $.utils.getUint16(0, this) as HttpMessage_Which;
  }
}
export class HttpRequestInit extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpRequestInit",
    id: "eae47d0497139b13",
    size: new $.ObjectSize(16, 3),
  };
  static _Headers: $.ListCtor<Header>;
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get method(): string {
    return $.utils.getText(0, this);
  }
  set method(value: string) {
    $.utils.setText(0, value, this);
  }
  get uri(): string {
    return $.utils.getText(1, this);
  }
  set uri(value: string) {
    $.utils.setText(1, value, this);
  }
  get version(): HttpVersion {
    return $.utils.getUint16(8, this) as HttpVersion;
  }
  set version(value: HttpVersion) {
    $.utils.setUint16(8, value, this);
  }
  _adoptHeaders(value: $.Orphan<$.List<Header>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownHeaders(): $.Orphan<$.List<Header>> {
    return $.utils.disown(this.headers);
  }
  get headers(): $.List<Header> {
    return $.utils.getList(2, HttpRequestInit._Headers, this);
  }
  _hasHeaders(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initHeaders(length: number): $.List<Header> {
    return $.utils.initList(2, HttpRequestInit._Headers, length, this);
  }
  set headers(value: $.List<Header>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  get hasBody(): boolean {
    return $.utils.getBit(80, this);
  }
  set hasBody(value: boolean) {
    $.utils.setBit(80, value, this);
  }
  toString(): string {
    return "HttpRequestInit_" + super.toString();
  }
}
export class HttpRequestEnd extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpRequestEnd",
    id: "bc503621daab0632",
    size: new $.ObjectSize(8, 0),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  toString(): string {
    return "HttpRequestEnd_" + super.toString();
  }
}
export class HttpRequestAbort extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpRequestAbort",
    id: "d398bed8ef2f867f",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get reason(): AbortReason {
    return $.utils.getUint16(8, this) as AbortReason;
  }
  set reason(value: AbortReason) {
    $.utils.setUint16(8, value, this);
  }
  get detail(): string {
    return $.utils.getText(0, this);
  }
  set detail(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string {
    return "HttpRequestAbort_" + super.toString();
  }
}
export class HttpResponseInit extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpResponseInit",
    id: "dc7bd14baf7c6e4d",
    size: new $.ObjectSize(24, 1),
  };
  static _Headers: $.ListCtor<Header>;
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  /**
   * 200, 404, ...
   *
   */
  get status(): number {
    return $.utils.getUint16(8, this);
  }
  set status(value: number) {
    $.utils.setUint16(8, value, this);
  }
  _adoptHeaders(value: $.Orphan<$.List<Header>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHeaders(): $.Orphan<$.List<Header>> {
    return $.utils.disown(this.headers);
  }
  get headers(): $.List<Header> {
    return $.utils.getList(0, HttpResponseInit._Headers, this);
  }
  _hasHeaders(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHeaders(length: number): $.List<Header> {
    return $.utils.initList(0, HttpResponseInit._Headers, length, this);
  }
  set headers(value: $.List<Header>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get hasBody(): boolean {
    return $.utils.getBit(80, this);
  }
  set hasBody(value: boolean) {
    $.utils.setBit(80, value, this);
  }
  /**
   * 0=unknown
   *
   */
  get contentLength(): bigint {
    return $.utils.getUint64(16, this);
  }
  set contentLength(value: bigint) {
    $.utils.setUint64(16, value, this);
  }
  toString(): string {
    return "HttpResponseInit_" + super.toString();
  }
}
export class HttpInterimResponse extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpInterimResponse",
    id: "fca1a2f0457d915f",
    size: new $.ObjectSize(16, 1),
  };
  static _Headers: $.ListCtor<Header>;
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  /**
   * 100-199
   *
   */
  get status(): number {
    return $.utils.getUint16(8, this);
  }
  set status(value: number) {
    $.utils.setUint16(8, value, this);
  }
  _adoptHeaders(value: $.Orphan<$.List<Header>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHeaders(): $.Orphan<$.List<Header>> {
    return $.utils.disown(this.headers);
  }
  get headers(): $.List<Header> {
    return $.utils.getList(0, HttpInterimResponse._Headers, this);
  }
  _hasHeaders(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHeaders(length: number): $.List<Header> {
    return $.utils.initList(0, HttpInterimResponse._Headers, length, this);
  }
  set headers(value: $.List<Header>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "HttpInterimResponse_" + super.toString();
  }
}
export class HttpBodyChunk extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpBodyChunk",
    id: "e9e3d78bd9d9c03b",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  _adoptData(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData(): $.Orphan<$.Data> {
    return $.utils.disown(this.data);
  }
  get data(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasData(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set data(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get seq(): number {
    return $.utils.getUint32(8, this);
  }
  set seq(value: number) {
    $.utils.setUint32(8, value, this);
  }
  get isLast(): boolean {
    return $.utils.getBit(96, this);
  }
  set isLast(value: boolean) {
    $.utils.setBit(96, value, this);
  }
  toString(): string {
    return "HttpBodyChunk_" + super.toString();
  }
}
export class HttpTrailers extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpTrailers",
    id: "a5e3baf5fe7303e1",
    size: new $.ObjectSize(8, 1),
  };
  static _Headers: $.ListCtor<Header>;
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  _adoptHeaders(value: $.Orphan<$.List<Header>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownHeaders(): $.Orphan<$.List<Header>> {
    return $.utils.disown(this.headers);
  }
  get headers(): $.List<Header> {
    return $.utils.getList(0, HttpTrailers._Headers, this);
  }
  _hasHeaders(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initHeaders(length: number): $.List<Header> {
    return $.utils.initList(0, HttpTrailers._Headers, length, this);
  }
  set headers(value: $.List<Header>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "HttpTrailers_" + super.toString();
  }
}
export class HttpResponseEnd extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpResponseEnd",
    id: "854bb133649d198a",
    size: new $.ObjectSize(8, 0),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  toString(): string {
    return "HttpResponseEnd_" + super.toString();
  }
}
export class HttpResponseAbort extends $.Struct {
  static readonly _capnp = {
    displayName: "HttpResponseAbort",
    id: "d544e3cab9996b62",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get reason(): AbortReason {
    return $.utils.getUint16(8, this) as AbortReason;
  }
  set reason(value: AbortReason) {
    $.utils.setUint16(8, value, this);
  }
  get detail(): string {
    return $.utils.getText(0, this);
  }
  set detail(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string {
    return "HttpResponseAbort_" + super.toString();
  }
}
export const HttpVersion = {
  /**
   * HTTP/1.1
   *
   */
  H1: 0,
  /**
   * HTTP/2
   * h3 is not supported;
   *
   */
  H2: 1,
} as const;
export type HttpVersion = (typeof HttpVersion)[keyof typeof HttpVersion];
export const AbortReason = {
  UNKNOWN: 0,
  TIMEOUT: 1,
  PEER_CLOSED: 2,
  RESET_BY_PEER: 3,
  CONNECTION_LOST: 4,
  CANCELLED: 5,
  PROTOCOL_ERROR: 6,
  FLOW_CONTROL: 7,
  OVERLOAD: 8,
} as const;
export type AbortReason = (typeof AbortReason)[keyof typeof AbortReason];
export class Header extends $.Struct {
  static readonly _capnp = {
    displayName: "Header",
    id: "84455f8078b27db9",
    size: new $.ObjectSize(0, 2),
  };
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  _adoptValue(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownValue(): $.Orphan<$.Data> {
    return $.utils.disown(this.value);
  }
  get value(): $.Data {
    return $.utils.getData(1, this);
  }
  _hasValue(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initValue(length: number): $.Data {
    return $.utils.initData(1, length, this);
  }
  set value(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  toString(): string {
    return "Header_" + super.toString();
  }
}
export const WebSocketOpcode = {
  CONTINUATION: 0,
  TEXT: 1,
  BINARY: 2,
  CLOSE: 3,
  PING: 4,
  PONG: 5,
} as const;
export type WebSocketOpcode =
  (typeof WebSocketOpcode)[keyof typeof WebSocketOpcode];
export class WebSocketFrame extends $.Struct {
  static readonly _capnp = {
    displayName: "WebSocketFrame",
    id: "c7a9aec0e8febcc8",
    size: new $.ObjectSize(24, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get fin(): boolean {
    return $.utils.getBit(64, this);
  }
  set fin(value: boolean) {
    $.utils.setBit(64, value, this);
  }
  get rsv1(): boolean {
    return $.utils.getBit(65, this);
  }
  set rsv1(value: boolean) {
    $.utils.setBit(65, value, this);
  }
  get rsv2(): boolean {
    return $.utils.getBit(66, this);
  }
  set rsv2(value: boolean) {
    $.utils.setBit(66, value, this);
  }
  get rsv3(): boolean {
    return $.utils.getBit(67, this);
  }
  set rsv3(value: boolean) {
    $.utils.setBit(67, value, this);
  }
  get opcode(): WebSocketOpcode {
    return $.utils.getUint16(10, this) as WebSocketOpcode;
  }
  set opcode(value: WebSocketOpcode) {
    $.utils.setUint16(10, value, this);
  }
  get masked(): boolean {
    return $.utils.getBit(68, this);
  }
  set masked(value: boolean) {
    $.utils.setBit(68, value, this);
  }
  get maskKey(): number {
    return $.utils.getUint32(12, this);
  }
  set maskKey(value: number) {
    $.utils.setUint32(12, value, this);
  }
  _adoptPayload(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownPayload(): $.Orphan<$.Data> {
    return $.utils.disown(this.payload);
  }
  get payload(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasPayload(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initPayload(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set payload(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get closeCode(): number {
    return $.utils.getUint16(16, this);
  }
  set closeCode(value: number) {
    $.utils.setUint16(16, value, this);
  }
  toString(): string {
    return "WebSocketFrame_" + super.toString();
  }
}
export const Control_Which = {
  PING: 0,
  PONG: 1,
  FLOW_WINDOW_UPDATE: 2,
  ERROR: 3,
  GO_AWAY: 4,
} as const;
export type Control_Which = (typeof Control_Which)[keyof typeof Control_Which];
export class Control extends $.Struct {
  static readonly PING = Control_Which.PING;
  static readonly PONG = Control_Which.PONG;
  static readonly FLOW_WINDOW_UPDATE = Control_Which.FLOW_WINDOW_UPDATE;
  static readonly ERROR = Control_Which.ERROR;
  static readonly GO_AWAY = Control_Which.GO_AWAY;
  static readonly _capnp = {
    displayName: "Control",
    id: "f19164b12011f28c",
    size: new $.ObjectSize(8, 1),
  };
  _adoptPing(value: $.Orphan<Ping>): void {
    $.utils.setUint16(0, 0, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownPing(): $.Orphan<Ping> {
    return $.utils.disown(this.ping);
  }
  get ping(): Ping {
    $.utils.testWhich("ping", $.utils.getUint16(0, this), 0, this);
    return $.utils.getStruct(0, Ping, this);
  }
  _hasPing(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initPing(): Ping {
    $.utils.setUint16(0, 0, this);
    return $.utils.initStructAt(0, Ping, this);
  }
  get _isPing(): boolean {
    return $.utils.getUint16(0, this) === 0;
  }
  set ping(value: Ping) {
    $.utils.setUint16(0, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptPong(value: $.Orphan<Pong>): void {
    $.utils.setUint16(0, 1, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownPong(): $.Orphan<Pong> {
    return $.utils.disown(this.pong);
  }
  get pong(): Pong {
    $.utils.testWhich("pong", $.utils.getUint16(0, this), 1, this);
    return $.utils.getStruct(0, Pong, this);
  }
  _hasPong(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initPong(): Pong {
    $.utils.setUint16(0, 1, this);
    return $.utils.initStructAt(0, Pong, this);
  }
  get _isPong(): boolean {
    return $.utils.getUint16(0, this) === 1;
  }
  set pong(value: Pong) {
    $.utils.setUint16(0, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptFlowWindowUpdate(value: $.Orphan<FlowWindowUpdate>): void {
    $.utils.setUint16(0, 2, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownFlowWindowUpdate(): $.Orphan<FlowWindowUpdate> {
    return $.utils.disown(this.flowWindowUpdate);
  }
  get flowWindowUpdate(): FlowWindowUpdate {
    $.utils.testWhich("flowWindowUpdate", $.utils.getUint16(0, this), 2, this);
    return $.utils.getStruct(0, FlowWindowUpdate, this);
  }
  _hasFlowWindowUpdate(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initFlowWindowUpdate(): FlowWindowUpdate {
    $.utils.setUint16(0, 2, this);
    return $.utils.initStructAt(0, FlowWindowUpdate, this);
  }
  get _isFlowWindowUpdate(): boolean {
    return $.utils.getUint16(0, this) === 2;
  }
  set flowWindowUpdate(value: FlowWindowUpdate) {
    $.utils.setUint16(0, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptError(value: $.Orphan<ErrorReport>): void {
    $.utils.setUint16(0, 3, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownError(): $.Orphan<ErrorReport> {
    return $.utils.disown(this.error);
  }
  get error(): ErrorReport {
    $.utils.testWhich("error", $.utils.getUint16(0, this), 3, this);
    return $.utils.getStruct(0, ErrorReport, this);
  }
  _hasError(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initError(): ErrorReport {
    $.utils.setUint16(0, 3, this);
    return $.utils.initStructAt(0, ErrorReport, this);
  }
  get _isError(): boolean {
    return $.utils.getUint16(0, this) === 3;
  }
  set error(value: ErrorReport) {
    $.utils.setUint16(0, 3, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptGoAway(value: $.Orphan<GoAway>): void {
    $.utils.setUint16(0, 4, this);
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownGoAway(): $.Orphan<GoAway> {
    return $.utils.disown(this.goAway);
  }
  get goAway(): GoAway {
    $.utils.testWhich("goAway", $.utils.getUint16(0, this), 4, this);
    return $.utils.getStruct(0, GoAway, this);
  }
  _hasGoAway(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initGoAway(): GoAway {
    $.utils.setUint16(0, 4, this);
    return $.utils.initStructAt(0, GoAway, this);
  }
  get _isGoAway(): boolean {
    return $.utils.getUint16(0, this) === 4;
  }
  set goAway(value: GoAway) {
    $.utils.setUint16(0, 4, this);
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "Control_" + super.toString();
  }
  which(): Control_Which {
    return $.utils.getUint16(0, this) as Control_Which;
  }
}
export class Ping extends $.Struct {
  static readonly _capnp = {
    displayName: "Ping",
    id: "e6be57830fd0468e",
    size: new $.ObjectSize(8, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  _adoptData(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData(): $.Orphan<$.Data> {
    return $.utils.disown(this.data);
  }
  get data(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasData(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set data(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "Ping_" + super.toString();
  }
}
export class Pong extends $.Struct {
  static readonly _capnp = {
    displayName: "Pong",
    id: "d6cf54316473cd3f",
    size: new $.ObjectSize(8, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  _adoptData(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownData(): $.Orphan<$.Data> {
    return $.utils.disown(this.data);
  }
  get data(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasData(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initData(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set data(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "Pong_" + super.toString();
  }
}
export class FlowWindowUpdate extends $.Struct {
  static readonly _capnp = {
    displayName: "FlowWindowUpdate",
    id: "e826c39bc9b96521",
    size: new $.ObjectSize(16, 0),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get availableSendBytes(): number {
    return $.utils.getUint32(8, this);
  }
  set availableSendBytes(value: number) {
    $.utils.setUint32(8, value, this);
  }
  toString(): string {
    return "FlowWindowUpdate_" + super.toString();
  }
}
export class ErrorReport extends $.Struct {
  static readonly _capnp = {
    displayName: "ErrorReport",
    id: "97f57fee4e4b6550",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get code(): number {
    return $.utils.getUint32(8, this);
  }
  set code(value: number) {
    $.utils.setUint32(8, value, this);
  }
  get message(): string {
    return $.utils.getText(0, this);
  }
  set message(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string {
    return "ErrorReport_" + super.toString();
  }
}
export class GoAway extends $.Struct {
  static readonly _capnp = {
    displayName: "GoAway",
    id: "d552cd9f59680575",
    size: new $.ObjectSize(16, 1),
  };
  get timestampMs(): bigint {
    return $.utils.getUint64(0, this);
  }
  set timestampMs(value: bigint) {
    $.utils.setUint64(0, value, this);
  }
  get lastMsgSeq(): number {
    return $.utils.getUint32(8, this);
  }
  set lastMsgSeq(value: number) {
    $.utils.setUint32(8, value, this);
  }
  get reason(): string {
    return $.utils.getText(0, this);
  }
  set reason(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string {
    return "GoAway_" + super.toString();
  }
}
HttpRequestInit._Headers = $.CompositeList(Header);
HttpResponseInit._Headers = $.CompositeList(Header);
HttpInterimResponse._Headers = $.CompositeList(Header);
HttpTrailers._Headers = $.CompositeList(Header);
